# Generated by Django 3.2.14 on 2022-07-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='회원 아이디')),
                ('uname', models.CharField(max_length=10, verbose_name='회원 이름')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('birth', models.DateField(verbose_name='회원 생년월일')),
                ('sex', models.CharField(max_length=20, verbose_name='회원 성별')),
                ('email', models.EmailField(max_length=254, verbose_name='회원 이메일')),
                ('phone', models.CharField(max_length=20, verbose_name='회원 전화번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='관리자 여부')),
                ('acc_allow', models.BooleanField(default=True, verbose_name='액세스 허용 사용 여부')),
            ],
        ),
    ]
