# Generated by Django 3.2.14 on 2022-07-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikey_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
